apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: oficina-mecanica
type: Opaque
stringData:
  JWT_SECRET: ${JWT_SECRET}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  CUSTOMER_JWT_PUBLIC_KEY: ${CUSTOMER_JWT_PUBLIC_KEY}